---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/photogrammetry
  label: Photogrammetry post
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: directory
  path: content/work
  label: Work post
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: directory
  path: content/photo
  label: Photo post
  create: all
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - photo-post
- type: directory
  path: content/blog
  label: Blog posts
  create: all
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
  new_doc_ext: mdx
upload_dir: static/images/forestry
public_path: "/images/forestry"
front_matter_path: "../../static/images/forestry"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
